name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: cypress/e2e/*

jobs:
  cypress-e2e-elecron:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.4

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 7f0807ba-7dfc-478a-892e-bd8426ef7fa1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  
